### ISSUE TITLE
connections with fsockopen or  curl ??

### ISSUE THREAD

**Issue by sudheer1994** [Karyazilim/DoyosiWhois#1]
what method do you use to connect to whois servers? 
fsockopen or curl?

Where can i find this in your code please point me in correct direction.

**Comment by Karyazilim** [comment]
This Script uses fsockopen. 
Open app/lib/web.php and search for whois function.
You will see.

**Comment by sudheer1994** [comment]
i have few more questions.
Does that do parallel request to whois servers or do single request at a time for bulk whois?

**Comment by Karyazilim** [comment]
> i have few more questions.
> Does that do parallel request to whois servers or do single request at a time for bulk whois?

Not single request for all domains. It calls a request for each domain. Also not paralel. It waits for getting domain info and does for another then. So asynchronous.

**Comment by sudheer1994** [comment]
thanks for clarifying mate.
